git:
  depth: 1
sudo: false
language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test --runInBand
  - yarn typecheck
  - yarn build -d release --public-url ./
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: release
  on:
    branch: master