git:
  depth: 1
sudo: false
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
  - yarn typecheck
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master